--- 
javascripts: 
- base: 
  - jrails
  - jquery
  - jquery-ui
  - jquery.cookie
  - tablefilter
  - misc
  - application
  - supernote
  - jquery.tablesorter
stylesheets: 
- base: 
  - tablesorter-style
  - wow
  - application
