--- 
javascripts: 
- base: 
  - supernote
  - jquery
  - jquery-ui
  - jrails
  - jquery.tablesorter
  - jquery.cookie
  - tablefilter
  - misc
  - application
stylesheets: 
- base: 
  - tablesorter-style
  - wow
  - application
