development:
   adapter: mysql
   database: guild_development
   username: root
   host: localhost
 development:
    adapter: mysql
    database: guild_production
    username: root
    host: localhost
